### ISSUE TITLE
Double consonants & Windows IME

### ISSUE THREAD

**Issue by Larsie13** [WaniKani/WanaKana#48] opened 2016-06-05 14:14 UTC
When using the Windows IME (Win7 Pro, x64), double consonants (っ and ッ) are not properly supported. For example, in order to enter **待って (まって)**, one would normally type 'matte'. Doing this without an IME or using Google's IME works fine. However, under Windows 7's IME, this ends up as **まっtえ**.

**Comment by seanblue** [comment] 2017-04-09 21:42
Are there plans to address this issue? It is still happening with the Windows IME on Windows 10.

**Comment by DJTB** [comment] 2017-07-23 18:10
I'd love to tackle this - but I don't have access to a windows environment to take a shot at debugging it. There's a *possibility* it can't be addressed anyway, depending on how the Microsoft IME handles cursor position.

Any PRs or explicit information on how the input field value changes are welcome.

**Comment by Larsie13** [comment] 2017-07-23 18:51
While I'm not a JS developer myself, it seems there are IME APIs available in JS (well, they're events, actually).
[This StackOverflow question](https://stackoverflow.com/questions/7316886/detecting-ime-input-before-enter-pressed-in-javascript) might help get you started.

**Comment by DJTB** [comment] 2017-07-29 11:59
I've added a flag to ignore any `input` events between `compositionstart` and `compositionend`.

This should actually improve performance minutely since we can exit much earlier before checking what the input is and whether it needs conversion (which of course kana IME input would not need). However `input` still fires once at the end of composition, so any romaji entered via an IME would still be converted :champagne:

I can't foresee any issues with this since we still have that final input capture after IME ends.
Anyone can give it a test by loading up `gh-pages/index.html` in https://github.com/WaniKani/WanaKana/tree/fix/microsoft-ime

@vietqhoang @mimshwright Thoughts before merging?

**Comment by seanblue** [comment] 2017-07-29 15:15
@DJTB Is there any way to test this without pulling down the repo and building it? If so, I'd be willing to try it out.

**Comment by DJTB** [comment] 2017-07-29 15:25
Available for a limited time only: http://a734dbbf.ngrok.io/
Let me know when done.

**Comment by DJTB** [comment] 2017-07-29 15:31
Seems I was wrong about that final input event!
Only affects users entering latin chars via an IME. 
It'll convert if they then input a space/anything afterwards.

I can probably tack on a conversion to `compositionend` if we want to have that functionality.
I'll try that now.

**Comment by seanblue** [comment] 2017-07-29 15:43
@DJTB I'm done testing. Looks like it fixes the bug. I also spot checked other IME and non-IME input data and everything seemed to work fine.

**Comment by DJTB** [comment] 2017-07-29 16:04
@seanblue 
Could you do the same tests again, including one situation where you enter latin characters with the IME?

I updated it to do a conversion after composition, to convert any latin characters, should they be entered via IME for whatever reason.

**Comment by seanblue** [comment] 2017-07-29 16:28
@DJTB I had already tested that case in the old version (since I saw your previous comment about it). It seems to work exactly the same in the new version.

However, I think there is one difference between the old and new versions, when using the hiragana input mode of the IME.

Typing 「わかｔｔ」in the IME and stopping before typing the last _a_ by pressing _Enter._

The previous version you had deployed kept 「わかｔｔ」(if I remember correctly).
The new version, when pressing _Enter_ converts it to 「わかっt」.

That change might be useful if you stop early by switching out of the IME or into romaji mode of the IME, since then typing the last _a_ would convert it to 「わかった」. If you had just pressed _Enter_ and stayed in hiragana mode, you don't really get anything from this since typing _a_ would result in 「わかっtあ」.

**Comment by DJTB** [comment] 2017-07-29 17:00
I think trying to support early exit from IME isn't something we can/should do.

Realistically you would input your kana [わか], press *Enter* then turn off IME or switch to romaji mode for [romaji], *Enter*, then back on again/kana mode. If you're using an IME, you shouldn't do half kana conversion then a few letters, then expect to complete those letters to kana with the input field auto conversion. I understand what you're saying about it being potentially useful, but it's an odd/abnormal use of the IME really. As opposed to a user entering [romaji] and nothing happening.

The previous deploy wouldn't convert [romaji] after pressing *Enter* (at least with the Google IME) without further/following input. I feel that if you press *Enter* then you've committed that text to the input field, and it should convert it if it is romaji.

Thanks for the testing!

**Comment by seanblue** [comment] 2017-07-29 17:22
Yeah, I wasn't trying to say that half-typed IME (kana) text should be converted. Since I couldn't reproduce the issue you described, I thought that's what you were trying to handle for some reason. Now it's clear that that wasn't you intention, so I guess that was just a side effect.

Perhaps the issue you described doesn't happen in the Microsoft IME, but either way everything seems to work as expected using it.

**Comment by DJTB** [comment] 2017-08-04 15:15
So it appears that mobile keyboards are also firing `compositionstart` & `compositionend` - mainly because they are composing to provide autocomplete suggestions. However they will only fire `compositionend` after user chooses an autosuggest option, enters a space, or taps enter key (bottom right of keyboard usually). So with the Microsoft fix, these keyboards won't convert anything during composition. :sob: 

Though I believe I found a better fix by only using `compositionupdate` rather than `compositionstart` and `compositionend`.

Only the Microsoft IME appears to hold onto double consonants until it receives a final vowel and converts all 3 chars at once.
`tt`... `tta` -> `った`
`kk` ... `kko` -> `っこ`

Whereas Google IME and Wanakana script opts for early conversion of the 2 chars at double syllable (excluding 'n')
`tt` -> `っt`
`っta` -> `った` 
`kk` -> `っｋ`
`っｋo` -> `っこ`

I've done some more testing, and if `compositionupdate` data (which fires **before** input event) ends in a double consonant we can do a one-off ignore of the following input event. Which will then convert once the third character is entered (like the Microsoft IME).

With Microsoft IME input, we would now skip on `かtt` and wait until we receive the next input which will actually be 'かった`, and then we don't have to convert anyway since it's all kana.

On mobile the input field will act the same, it'll wait at `かtt` until it receives `かtta` -> `がった`. Minor change, but only visually: `tt` vs previous style `っt`, the result is still the same.

With Google IME input, this won't occur since we never receive the double consonants (it converts them early).

So far so good, I'll flesh out tests and then ask you @seanblue for another check~

**Comment by seanblue** [comment] 2017-08-05 01:25
Sure, just let me know. I'll run through some tests on my computer and iPhone.

**Comment by seanblue** [comment] 2017-08-05 01:35
@DJTB Maybe I'm misunderstanding the mobile issue you mentioned, but it looks like it's working fine on `wanakana.com` using my iPhone's IME. What mobile device were you seeing this issue on? And can you give specific steps to reproduce the issue so I know what to look for?

**Comment by DJTB** [comment] 2017-08-05 08:07
Android / Nexus, stock Google keyboard (GBoard). 
I've had a few user reports and tested myself.

**Comment by DJTB** [comment] 2017-08-05 09:06
Ok @seanblue can you give iPhone/Microsoft IME a shot at http://821d54e5.ngrok.io/

Want to confirm (alongside normal conversion) cases with double consonants like:
`matta` -> `まった`
`gasshou` -> `がっしょう`
`kekkon` -> `けっこん`
`donnna` -> `どんな` (should not have っ)

I'll check Android.

**Comment by seanblue** [comment] 2017-08-05 17:48
Yeah, it looks like the iPhone's IME works the same as how you described the Google IME, converting the double consonant early.

**Comment by DJTB** [comment] 2017-08-05 18:03
I'm pretty sure my new solution works for the affected mobile keyboards and Microsoft IME.
Can you do your worst at http://5b30042e.ngrok.io/gh-pages for me?

**Comment by seanblue** [comment] 2017-08-05 18:21
Seems to work fine using the Microsoft IME and the iPhone IME.

**Comment by DJTB** [comment] 2017-08-05 20:13
Confirmed mobile input with affected users.

**Closed by DJTB** 2017-08-05 20:13 UTC
